# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
    # primary image for building app
    - image: circleci/golang:1.13

    # service images available at `host: localhost`
    - image: circleci/postgres:11-alpine
      environment:
        POSTGRES_USER: dev-user
        POSTGRES_PASSWORD: dev-secret
        POSTGRES_DB: my_postgres_db

    branches:
      ignore:
      - develop

    working_directory: /go/src/github.com/swisscom/backman

    steps:
      - checkout
      # unit tests
      - run: make test

      # prepare for docker
      - setup_remote_docker:
          docker_layer_caching: true

      # run minio server
      - run:
          name: run minIO server
          command: |
            docker run -d -p 9000:9000 --name minio \
              -e "MINIO_ACCESS_KEY=deadbeef-beefdead" \
              -e "MINIO_SECRET_KEY=beefbeefbeefbeef" \
              minio/minio server /data

      # postgres integration tests
      - run:
          name: install Postgres client
          command: sudo apt install -y postgresql-client || true
      - run: make postgres-test
